/// <reference path="../typings/mocha/mocha.d.ts"/>
'use strict';

var Student = require("../Student")
, Course = require("../Course")
, chai = require("chai")
, should = chai.should()
, expect = chai.expect
;

describe("Student", function () {
    var studentName = "John Doe",
        studentGrade = 5;

    it(' should save the info on the student and create an id when created', function(){
        var student = student.create(studentName, studentGrade);

        should.exist(student.name);
        student.name.should.equal(studentName)
        //tests that the student name exists and matches the previous variable

        should.exist(studentGrade)
        student.grade.should.equal(studentGrade)
        //tests that the student grade exists and matches the previous variable

        should.exist(student.id);
        //this will be generated by the uuid module, while we cant check the specific value it can be checked that it exists
    });

    it("should increase the students grade by 1 when advanceGrade is called", function(){
        var student = Student.create(studentName, studentGrade);
        // duplication here is fine as it gives context for the test, meaning someone looking over the specific test wouldnt have to also find the before each to understand what is happening

        Student.advanceGrade();

        student.grade.should.equal(studentGrade+1);
    });
});
